<?php

/*******************************************************
NOTE: This is a translatable file generated by IP.Board 3.2.0 Beta 1 (32000) on Tue, 21 Jun 2011 21:35:53 +0000 by Edgar_94_
PLEASE set your text editor to save this document as UTF-8 regardless of your board's character-set
*******************************************************/



$lang = array( 
'ls_view_more_forums'				=> "Ver más foros",
'ls_forums'				=> "Foros",
'ls_groupresults'				=> "Hay grupos de ajustes que corresponden a su término de búsqueda &raquo;",
'ls_view_more_groups'				=> "Ver más grupos",
'ls_grouptitles'				=> "Grupos",
'ls_view_more_mem'				=> "Ver más miembros",
'lsnoresults'				=> "No se encontraron resultados",
'ls_members'				=> "Miembros",
'livesearchmemid'				=> "ID: ",
'ls_acppages'				=> "Páginas del PCA",
'ls_help'				=> "Archivos de Ayuda",
'ls_settings'				=> "Ajustes",
'ls_quick_search'				=> "Búsqueda Rápida",
'ls_view_more_acp'				=> "Ver más páginas del PCA",
'ls_view_more_help'				=> "Ver más archivos de ayuda",
'ls_view_more_settings'				=> "Ver más ajustes",
'ls_groups'				=> "Groups Form",
 ); 
